# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Face_book\face_book.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 665)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.leftBody = QtWidgets.QWidget(self.centralWidget)
        self.leftBody.setMaximumSize(QtCore.QSize(500, 16777215))
        self.leftBody.setObjectName("leftBody")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.leftBody)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openCamera = QtWidgets.QPushButton(self.leftBody)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.openCamera.setFont(font)
        self.openCamera.setObjectName("openCamera")
        self.horizontalLayout.addWidget(self.openCamera)
        self.recommend_pushButton = QtWidgets.QPushButton(self.leftBody)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.recommend_pushButton.setFont(font)
        self.recommend_pushButton.setObjectName("recommend_pushButton")
        self.horizontalLayout.addWidget(self.recommend_pushButton)
        self.Info_pushButton = QtWidgets.QPushButton(self.leftBody)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Info_pushButton.setFont(font)
        self.Info_pushButton.setObjectName("Info_pushButton")
        self.horizontalLayout.addWidget(self.Info_pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.CameraLabel = QtWidgets.QLabel(self.leftBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CameraLabel.sizePolicy().hasHeightForWidth())
        self.CameraLabel.setSizePolicy(sizePolicy)
        self.CameraLabel.setMinimumSize(QtCore.QSize(0, 200))
        self.CameraLabel.setObjectName("CameraLabel")
        self.verticalLayout_2.addWidget(self.CameraLabel)
        self.groupBox_2 = QtWidgets.QGroupBox(self.leftBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Name_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Name_label.setFont(font)
        self.Name_label.setText("")
        self.Name_label.setObjectName("Name_label")
        self.gridLayout.addWidget(self.Name_label, 0, 1, 1, 1)
        self.Num_label_1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Num_label_1.setFont(font)
        self.Num_label_1.setObjectName("Num_label_1")
        self.gridLayout.addWidget(self.Num_label_1, 0, 2, 1, 1)
        self.Num_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Num_label.setFont(font)
        self.Num_label.setText("")
        self.Num_label.setObjectName("Num_label")
        self.gridLayout.addWidget(self.Num_label, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.Class_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Class_label.setFont(font)
        self.Class_label.setText("")
        self.Class_label.setObjectName("Class_label")
        self.gridLayout.addWidget(self.Class_label, 1, 1, 1, 1)
        self.Num_label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Num_label_3.setFont(font)
        self.Num_label_3.setObjectName("Num_label_3")
        self.gridLayout.addWidget(self.Num_label_3, 1, 2, 1, 1)
        self.Major_label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Major_label.setFont(font)
        self.Major_label.setText("")
        self.Major_label.setObjectName("Major_label")
        self.gridLayout.addWidget(self.Major_label, 1, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.leftBody)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LogoLabel = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LogoLabel.sizePolicy().hasHeightForWidth())
        self.LogoLabel.setSizePolicy(sizePolicy)
        self.LogoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.LogoLabel.setObjectName("LogoLabel")
        self.gridLayout_2.addWidget(self.LogoLabel, 0, 0, 1, 1)
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.groupBox)
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.gridLayout_2.addWidget(self.textBrowser_12, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.leftBody)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.time_label = QtWidgets.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.verticalLayout_3.addWidget(self.time_label)
        self.book_tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.book_tabWidget.setFont(font)
        self.book_tabWidget.setObjectName("book_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.favor_listWidget = QtWidgets.QListWidget(self.tab)
        self.favor_listWidget.setObjectName("favor_listWidget")
        self.gridLayout_4.addWidget(self.favor_listWidget, 0, 0, 1, 1)
        self.book_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.class_listWidget = QtWidgets.QListWidget(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.class_listWidget.setFont(font)
        self.class_listWidget.setObjectName("class_listWidget")
        self.gridLayout_5.addWidget(self.class_listWidget, 0, 0, 1, 1)
        self.book_tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.major_listWidget = QtWidgets.QListWidget(self.tab_3)
        self.major_listWidget.setObjectName("major_listWidget")
        self.gridLayout_6.addWidget(self.major_listWidget, 0, 0, 1, 1)
        self.book_tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.hot_listWidget = QtWidgets.QListWidget(self.tab_4)
        self.hot_listWidget.setObjectName("hot_listWidget")
        self.gridLayout_7.addWidget(self.hot_listWidget, 0, 0, 1, 1)
        self.book_tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.history_listWidget = QtWidgets.QListWidget(self.tab_5)
        self.history_listWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.history_listWidget.setObjectName("history_listWidget")
        self.gridLayout_8.addWidget(self.history_listWidget, 0, 0, 1, 1)
        self.book_tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Newbook_listWidget = QtWidgets.QListWidget(self.tab_6)
        self.Newbook_listWidget.setObjectName("Newbook_listWidget")
        self.verticalLayout.addWidget(self.Newbook_listWidget)
        self.book_tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_3.addWidget(self.book_tabWidget)
        self.Search_Book_groupBox = QtWidgets.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Search_Book_groupBox.setFont(font)
        self.Search_Book_groupBox.setObjectName("Search_Book_groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Search_Book_groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Search_listWidget = QtWidgets.QListWidget(self.Search_Book_groupBox)
        self.Search_listWidget.setObjectName("Search_listWidget")
        self.gridLayout_3.addWidget(self.Search_listWidget, 1, 0, 1, 3)
        self.Serach_pushButton = QtWidgets.QPushButton(self.Search_Book_groupBox)
        self.Serach_pushButton.setObjectName("Serach_pushButton")
        self.gridLayout_3.addWidget(self.Serach_pushButton, 0, 1, 1, 1)
        self.Clera_pushButton = QtWidgets.QPushButton(self.Search_Book_groupBox)
        self.Clera_pushButton.setObjectName("Clera_pushButton")
        self.gridLayout_3.addWidget(self.Clera_pushButton, 0, 2, 1, 1)
        self.Search_line = QtWidgets.QLineEdit(self.Search_Book_groupBox)
        self.Search_line.setObjectName("Search_line")
        self.gridLayout_3.addWidget(self.Search_line, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.Search_Book_groupBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.book_tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于人脸识别的智能图书推荐系统"))
        self.openCamera.setText(_translate("MainWindow", "打开摄像头"))
        self.recommend_pushButton.setText(_translate("MainWindow", "开始推荐"))
        self.Info_pushButton.setText(_translate("MainWindow", "信息采集"))
        self.CameraLabel.setText(_translate("MainWindow", "视频显示"))
        self.groupBox_2.setTitle(_translate("MainWindow", "个人信息"))
        self.label_2.setText(_translate("MainWindow", "姓名："))
        self.Num_label_1.setText(_translate("MainWindow", "学号："))
        self.label_4.setText(_translate("MainWindow", "年级："))
        self.Num_label_3.setText(_translate("MainWindow", "专业:"))
        self.groupBox.setTitle(_translate("MainWindow", "操作说明"))
        self.LogoLabel.setText(_translate("MainWindow", "TextLabel"))
        self.textBrowser_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt; font-weight:600;\">软件使用说明：</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">1.点击左上方的打开摄像头按钮，打开摄像头。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">2.点击左上方的图书推荐按钮，开始进行人脸识别以及图书推荐。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">3.点击左上方的信息采集按钮，进行信息采集。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">4.右下方输入图书名，点击搜索按钮进行图书搜索。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">             </span><span style=\" font-size:11pt; font-weight:600;\">@少年郎版权所有</span></p></body></html>"))
        self.time_label.setText(_translate("MainWindow", "time"))
        self.book_tabWidget.setTabText(self.book_tabWidget.indexOf(self.tab), _translate("MainWindow", "爱好推荐"))
        self.book_tabWidget.setTabText(self.book_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "年级推荐"))
        self.book_tabWidget.setTabText(self.book_tabWidget.indexOf(self.tab_3), _translate("MainWindow", "专业推荐"))
        self.book_tabWidget.setTabText(self.book_tabWidget.indexOf(self.tab_4), _translate("MainWindow", "热门推荐"))
        self.book_tabWidget.setTabText(self.book_tabWidget.indexOf(self.tab_5), _translate("MainWindow", "历史记录"))
        self.book_tabWidget.setTabText(self.book_tabWidget.indexOf(self.tab_6), _translate("MainWindow", "新书展区"))
        self.Search_Book_groupBox.setTitle(_translate("MainWindow", "搜索"))
        self.Serach_pushButton.setText(_translate("MainWindow", "搜索"))
        self.Clera_pushButton.setText(_translate("MainWindow", "清空"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

