# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Face_book\information.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Information(object):
    def setupUi(self, Information):
        Information.setObjectName("Information")
        Information.resize(768, 440)
        self.centralWidget = QtWidgets.QWidget(Information)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Pic_label = QtWidgets.QLabel(self.centralWidget)
        self.Pic_label.setMinimumSize(QtCore.QSize(0, 340))
        self.Pic_label.setMaximumSize(QtCore.QSize(410, 16777215))
        self.Pic_label.setObjectName("Pic_label")
        self.gridLayout.addWidget(self.Pic_label, 0, 0, 2, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Name_label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Name_label_2.setFont(font)
        self.Name_label_2.setObjectName("Name_label_2")
        self.gridLayout_2.addWidget(self.Name_label_2, 0, 0, 1, 1)
        self.name_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.gridLayout_2.addWidget(self.name_lineEdit, 0, 1, 1, 1)
        self.Num_label_1 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Num_label_1.setFont(font)
        self.Num_label_1.setObjectName("Num_label_1")
        self.gridLayout_2.addWidget(self.Num_label_1, 0, 2, 1, 1)
        self.num_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.num_lineEdit.setObjectName("num_lineEdit")
        self.gridLayout_2.addWidget(self.num_lineEdit, 0, 3, 1, 1)
        self.Class_label_4 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Class_label_4.setFont(font)
        self.Class_label_4.setObjectName("Class_label_4")
        self.gridLayout_2.addWidget(self.Class_label_4, 1, 0, 1, 1)
        self.grade_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.grade_comboBox.setObjectName("grade_comboBox")
        self.grade_comboBox.addItem("")
        self.grade_comboBox.addItem("")
        self.grade_comboBox.addItem("")
        self.grade_comboBox.addItem("")
        self.grade_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.grade_comboBox, 1, 1, 1, 3)
        self.Major_label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Major_label_3.setFont(font)
        self.Major_label_3.setObjectName("Major_label_3")
        self.gridLayout_2.addWidget(self.Major_label_3, 2, 0, 1, 1)
        self.major_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.major_comboBox.setObjectName("major_comboBox")
        self.major_comboBox.addItem("")
        self.major_comboBox.addItem("")
        self.major_comboBox.addItem("")
        self.major_comboBox.addItem("")
        self.major_comboBox.addItem("")
        self.major_comboBox.addItem("")
        self.major_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.major_comboBox, 2, 1, 1, 3)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_2.addWidget(self.checkBox_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_3.addWidget(self.checkBox_6)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 2)
        self.Save_pushButton = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Save_pushButton.setFont(font)
        self.Save_pushButton.setObjectName("Save_pushButton")
        self.gridLayout.addWidget(self.Save_pushButton, 2, 1, 1, 1)
        self.Close_pushButton = QtWidgets.QPushButton(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Close_pushButton.setFont(font)
        self.Close_pushButton.setObjectName("Close_pushButton")
        self.gridLayout.addWidget(self.Close_pushButton, 2, 2, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralWidget)
        self.textBrowser.setMaximumSize(QtCore.QSize(410, 16777215))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 2, 0, 1, 1)
        Information.setCentralWidget(self.centralWidget)

        self.retranslateUi(Information)
        self.grade_comboBox.setCurrentIndex(0)
        self.major_comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Information)

    def retranslateUi(self, Information):
        _translate = QtCore.QCoreApplication.translate
        Information.setWindowTitle(_translate("Information", "信息采集界面"))
        self.Pic_label.setText(_translate("Information", "TextLabel"))
        self.groupBox_2.setTitle(_translate("Information", "个人信息"))
        self.Name_label_2.setText(_translate("Information", "姓名："))
        self.Num_label_1.setText(_translate("Information", "学号："))
        self.Class_label_4.setText(_translate("Information", "年级："))
        self.grade_comboBox.setItemText(0, _translate("Information", "——请选择年级——"))
        self.grade_comboBox.setItemText(1, _translate("Information", "2015级"))
        self.grade_comboBox.setItemText(2, _translate("Information", "2016级"))
        self.grade_comboBox.setItemText(3, _translate("Information", "2017级"))
        self.grade_comboBox.setItemText(4, _translate("Information", "2018级"))
        self.Major_label_3.setText(_translate("Information", "专业:"))
        self.major_comboBox.setItemText(0, _translate("Information", "——请选择专业——"))
        self.major_comboBox.setItemText(1, _translate("Information", "哲学"))
        self.major_comboBox.setItemText(2, _translate("Information", "经济"))
        self.major_comboBox.setItemText(3, _translate("Information", "数学"))
        self.major_comboBox.setItemText(4, _translate("Information", "自动化"))
        self.major_comboBox.setItemText(5, _translate("Information", "计算机科学与技术"))
        self.major_comboBox.setItemText(6, _translate("Information", "其他"))
        self.groupBox.setTitle(_translate("Information", "喜好选择"))
        self.checkBox.setText(_translate("Information", "经济"))
        self.checkBox_2.setText(_translate("Information", "哲学"))
        self.checkBox_3.setText(_translate("Information", "数学"))
        self.checkBox_4.setText(_translate("Information", "计算机科学与技术"))
        self.checkBox_5.setText(_translate("Information", "自动化"))
        self.checkBox_6.setText(_translate("Information", "其他"))
        self.Save_pushButton.setText(_translate("Information", "保存"))
        self.Close_pushButton.setText(_translate("Information", "返回"))
        self.textBrowser.setHtml(_translate("Information", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">点击保存按钮，保存信息，并自动保存到云端。</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">点击返回按钮，返回主窗体。</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Information = QtWidgets.QMainWindow()
    ui = Ui_Information()
    ui.setupUi(Information)
    Information.show()
    sys.exit(app.exec_())

